# Generated by Django 5.2.10 on 2026-03-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
