# Generated by Django 5.2.10 on 2026-03-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_verification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
