# Generated by Django 5.2.10 on 2026-03-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wishlistitem_unique_together_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('profile', 'product')},
        ),
    ]
