# Generated by Django 5.2.10 on 2026-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('card', 'Cartão')], max_length=20, null=True),
        ),
    ]
